version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coveralls
    versions:
    - 3.0.1
  - dependency-name: importlib-metadata
    versions:
    - 3.6.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
